### ISSUE TITLE
Excel Download

### ISSUE THREAD

**Issue by glebovpavel** [mgoricki/orclapex-ig-cheat-sheet#2]
Hi Marko,

Thank you for great work, it is really helpful. 

probably for APEX Developers can be interesting how one can get formatted Excel-File from Interactive Grid using java script (https://github.com/glebovpavel/IR_to_MSExcel). 

Regards,
Pavel

**Comment by mgoricki** [comment]
Ok, thanks, but it's not IG Cheat Sheet issue.
